### ISSUE TITLE
Namespace is missing in documentation

### ISSUE THREAD

**Issue by michelmoorlag** [Brainflab/XamaRed.Forms.Svg#1]
It works like a charm but it took me some time to find out the missing namespace: xmlns:svg="clr-namespace:XamaRed.Forms.Svg;assembly=XamaRed.Forms.Svg"
If you can add this to your documentation you will save future users some time.

**Comment by Brainflab** [comment]
Done, thank you and sorry for your time.

**Comment by michelmoorlag** [comment]
You are welcome and thank YOU for creating this great plugin :)
And time is relative as Einstein used to say. The couple of minutes it took to find the namespace is peanuts compared to the time it would have taken to write my own svg support.
